spring:
  application.name: 07highValueCustomer
  kafka:
    bootstrap-servers: localhost:9092
    client-id: ${spring.application.name}
    properties:
      schema.registry.url: "http://localhost:8081"
    admin:
      auto-create: false
    consumer:
      properties:
        session.timeout.ms: 10000
        spring.json.value.default.type: "com.thinkport.producer.model.ClickJson"
        spring.json.trusted.packages: "*"
    streams:
      properties:
        session.timeout.ms: 10000
        spring.json.value.default.type: "com.thinkport.producer.model.ClickJson"
        spring.json.trusted.packages: "*"
kafka-topics:
  article-in: shop.articles
  cart-item-in: shop.carts
  order-placed-in: shop.orders.placed
  order-reduced-out: shop.order.reduced
  shop-user-total: shop.user.total
server.port: -1
logging:
  level:
    root: INFO
management:
  server.port: 8077
  endpoint:
    health.enabled: true
    prometheus.enabled: true
  health:
    key:
      enabled: livenessstate,readinessstate
    defaults:
      enabled: false
    probes:
      enabled: true
  endpoints:
    enabled-by-default: false
    web.exposure.include: '*'