spring:
  application.name: 03avro
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    bootstrap-servers: localhost:9092
    client-id: ${spring.application.name}
    properties:
      schema.registry.url: "{TODO: Enter URL}"
      specific.avro.reader: true
    consumer:
      group-id: ${spring.application.name}
      auto-offset-reset: earliest
      key-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        session.timeout.ms: 10000
        spring.json.value.default.type: "com.thinkport.producer.model.ClickJson"
        spring.json.trusted.packages: "*"
kafka-topics:
  clicks-in: shop.clicks.raw
  clicks-out: shop.clicks.avro