spring:
  application.name: 06stateful
  kafka:
    bootstrap-servers: localhost:9092
    client-id: ${spring.application.name}
    properties:
      schema.registry.url: "http://localhost:8081"
    admin:
      auto-create: false
    consumer:
      properties:
        session.timeout.ms: 10000
        spring.json.value.default.type: "com.thinkport.producer.model.ClickJson"
        spring.json.trusted.packages: "*"
    streams:
      properties:
        session.timeout.ms: 10000
        spring.json.value.default.type: "com.thinkport.producer.model.ClickJson"
        spring.json.trusted.packages: "*"
kafka-topics:
  clicks-in: shop.clicks.filtered
  clicks-out: shop.clicks.avro
  users-in: shop.users
  users-out: user.clicks.frauds
server.port: -1
logging:
  level:
    root: INFO
management:
  server.port: 8077
  endpoint:
    health.enabled: true
    prometheus.enabled: true
  health:
    key:
      enabled: livenessstate,readinessstate
    defaults:
      enabled: false
    probes:
      enabled: true
  endpoints:
    enabled-by-default: false
    web.exposure.include: '*'