spring:
  application.name: producer
  kafka:
    bootstrap-servers: localhost:9092
    client-id: ${spring.application.name}
    properties:
      schema.registry.url: "http://localhost:8081"
server.port: -1